### ISSUE TITLE
Get-RscMssqlInstance -List returning invalid object types

### ISSUE THREAD

**Issue by McDBAOptPHC** [rubrikinc/rubrik-powershell-sdk#78] opened 2024-04-10 14:36 UTC
We are unable to run Get-RscMssqlInstance with any of the parameters which looks to already be a reported issue, but if I run it with the -List switch I am not getting back any of the enrolled instances, instead I am getting host and cluster objects: 
 (Get-RscMssqlInstance -List).objectType
Output:
WINDOWS_CLUSTER
PHYSICAL_HOST
PHYSICAL_HOST
PHYSICAL_HOST
PHYSICAL_HOST
PHYSICAL_HOST
WINDOWS_CLUSTER
PHYSICAL_HOST
PHYSICAL_HOST
WINDOWS_CLUSTER
PHYSICAL_HOST
PHYSICAL_HOST
PHYSICAL_HOST
WINDOWS_CLUSTER
PHYSICAL_HOST
PHYSICAL_HOST
PHYSICAL_HOST
PHYSICAL_HOST
PHYSICAL_HOST
WINDOWS_CLUSTER
PHYSICAL_HOST

**Comment by clumnah** [comment] 2024-04-12 17:39
Hello, I believe this is a different issue than the one we spoke about over email, correct?

The above output is correct and by design. Take a look at the below output. 
```
AuthorizedOperations        : 
ObjectType                  : PHYSICAL_HOST
OsType                      : 
SlaAssignment               : UNASSIGNED
ConfiguredSlaDomain         : 
EffectiveRetentionSlaDomain : 
EffectiveSlaDomain          : RubrikSecurityCloud.Types.GlobalSlaReply
PendingSla                  : 
ReplicatedObjects           : 
AgentId                     : {62fb9ac5-79b1-4355-8531-fd61c37d8740}
CbtStatus                   : Enabled
CdmId                       : 0c0fb77d-d959-494d-af5f-bdb0f230c46a
CdmLink                     : 
DefaultCbt                  : 
Id                          : f61620b7-57ed-5368-8407-21a9f8477df2
IpAddresses                 : 
IsArchived                  : False
IsChangelistEnabled         : False
IsOracleHost                : False
Name                        : sh2-qstar-w1
NasMigrationInfo            : 
NasVendorType               : 
NumWorkloadDescendants      : 12
OsName                      : 
ReplicatedObjectCount       : 
SlaPauseStatus              : False
VfdState                    : Installed
AllOrgs                     : 
Cluster                     : 
ConnectionStatus            : 
DescendantConnection        : 
EffectiveSlaSourceObject    : 
HostVolumes                 : 
LatestUserNote              : 
LogicalPath                 : 
OracleUserDetails           : 
PendingObjectDeletionStatus : 
PhysicalChildConnection     : RubrikSecurityCloud.Types.PhysicalHostPhysicalChildTypeConnection
PhysicalPath                : 
PrimaryClusterLocation      : 
SnapshotDistribution        : 
```

You can easily tell what host this SQL Server is and then instance information itself would be found under the `PhysicalChildConnection` object. This is because if we only returned back the instance object itself, it would look like the below. 

```
AuthorizedOperations        : 
ObjectType                  : MSSQL_INSTANCE
SlaAssignment               : DIRECT
ConfiguredSlaDomain         : 
EffectiveRetentionSlaDomain : 
EffectiveSlaDomain          : RubrikSecurityCloud.Types.GlobalSlaReply
PendingSla                  : 
ReplicatedObjects           : 
HasLogConfigFromSla         : True
HostLogRetention            : 
Id                          : cbdf206e-6dc2-5048-ac1b-0ca93283c3b7
LogBackupFrequencyInSeconds : 
LogBackupRetentionInHours   : 
Name                        : MSSQLSERVER
NumWorkloadDescendants      : 12
ReplicatedObjectCount       : 
SlaPauseStatus              : False
UnprotectableReasons        : 
AllOrgs                     : 
Cluster                     : RubrikSecurityCloud.Types.Cluster
DescendantConnection        : 
EffectiveSlaSourceObject    : 
LatestUserNote              : 
LogicalChildConnection      : 
LogicalPath                 : 
PendingObjectDeletionStatus : 
PhysicalPath                : {sh1-sql19ag-1a.rubrikdemo.com}
PrimaryClusterLocation      : 
SnapshotDistribution        : 
```
There was not a way to look at the above data and see SQL Server Host this instance belonged to. Only very recently, was the `PhysicalPath` populated with the host.

**Comment by McDBAOptPHC** [comment] 2024-04-12 19:30
Ahh okay, so yeah if I do this  (Get-RSCMSsqlInstance -List | Where-Object -FilterScript {$_.Name -eq $TargetHost.Name}).PhysicalChildConnection so if that's working as designed I'll mark this as closed.

**Comment by clumnah** [comment] 2024-04-12 19:33
Hopefully you are not having to write your query like that and can just use Get-RscMssqlDatabase -HostName instead. :-)

**Comment by SahFari** [comment] 2024-04-15 06:18
Get-RscMssqlDatabase: A parameter cannot be found that matches parameter name 'HostName'.

**Comment by clumnah** [comment] 2024-04-17 02:57
Are you on version 1.0?
Can you share the command you used to get that error?

**Comment by SahFari** [comment] 2024-04-17 05:55
We are at CDM 8.1.3-p7 and are planning to upgrade to CDM 9.1.x on May 7.

PS C:\PS> $PSVersionTable     

Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\PS>
PS C:\PS> Get-InstalledModule RubrikSecurityCloud

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
1.0                  RubrikSecurityCloud                 PSGallery            PowerShell Module for Rubrik Security Cloud. GraphQL schema version: v20240325-21 .

PS C:\PS>
PS C:\PS> $Server = "SQLLAB01"
PS C:\PS>
PS C:\PS> Get-RscMssqlDatabase -HostName $Server
Get-RscMssqlDatabase: A parameter cannot be found that matches parameter name 'HostName'.
PS C:\PS>

**Comment by clumnah** [comment] 2024-04-17 13:25
My mistake. I misread your original statement and thought it was about Get-RscMssqlInstance which is where the original problem came from.

Get-RscMssqlDatabase does not have a -Hostname parameter, it has a RscMssqlInstance parameter. That value would be gotten from Get-RscMssqlInstance.

**Comment by SahFari** [comment] 2024-04-17 13:35
I got the command from the example in 
https://www.powershellgallery.com/packages/RubrikSecurityCloud/1.0/Content/Toolkit%5CPublic%5CGet-RscMssqlDatabase.ps1

$RscMssqlInstance = **Get-RscMssqlInstance -HostName** sql19.demo.com -clusterID hja87-ajb43-v4avna-hnjag
Get-RscMssqlDatabase -Name AdventureWorks2019 -RscMssqlInstance $RscMssqlInstance

and as you said, there is not parameter for  -Hostname.

**Comment by clumnah** [comment] 2024-04-17 13:42
I am still confused then as to the issue. Can you state your issue to help me understand? I am not sure on next steps on how to help.

**Comment by SahFari** [comment] 2024-04-17 14:46
I think we misunderstand each other! 

My issue was with example in [Get-RscMssqlDatabase.ps1] and I think you need to take a look at it (Get-RscMssqlInstance -HostName in  [Get-RscMssqlDatabase.ps1]  )

And you wrote earlier: "Hopefully you are not having to write your query like that and can just use Get-RscMssqlDatabase -HostName instead. :-) "

**Comment by clumnah** [comment] 2024-04-17 15:33
Ah..yes….I agree :-) 

Yes, my earlier comment was a typo it should have been Get-RscMssqlInstance -Hostname.

**Comment by clumnah** [comment] 2024-04-17 15:34
To close the overall thread, is it ok to close this issue out?

**Comment by McDBAOptPHC** [comment] 2024-04-17 15:35
Yeah we should be good to close this one out.


Thanks,

____________________

Michael McConnell
Database Administrator / ETL/Cogito Administrator | Optum Insight
Supporting ProHealth Care

262-696-0332
***@***.******@***.***>

N17 W24100 Riverwood Dr. Suite 100
Waukesha, WI 53188

**Comment by SahFari** [comment] 2024-04-17 15:38
Yes, I agree! 

Thanks

**Closed** 2024-04-17 15:43 UTC
