### ISSUE TITLE
Cannot connect to RSC

### ISSUE THREAD

**Issue by sayujshrestha** [rubrikinc/rubrik-powershell-sdk#24] opened 2023-10-23 15:52 UTC
I followed exactly as the readme says. Installed the module and ran _Set-RscServiceAccountFile_ to generate an encrypted service account file and store it in a default location. But when I run _Connect-Rsc_ command it gives me the following error. Am I missing anything. Note: I have MFA enabled in RSC.

> PS C:\Windows\system32> Connect-Rsc
Connect-Rsc : One or more errors occurred.
At line:1 char:1
+ Connect-Rsc
+ ~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-Rsc], AggregateException
    + FullyQualifiedErrorId : UnableToAuthenticateToRubrikSecurityCloud,RubrikSecurityCloud.PowerShell.Cmdlets.Connect
   _Rsc

**Comment by rynardtspies** [comment] 2023-11-02 11:17
Hi @sayujshrestha 

Thank you for bringing this to our attention. I have been able to reproduce this on Windows PowerShell 5.1. This issue does not occur on PowerShell (Core) 5.2+

We have identified the cause and are working on a fix.

Regards

Rynardt

**Comment by sayujshrestha** [comment] 2023-11-02 12:59
Yes, it is 5.1.19041.3570. Thank you for your attention. I will be eagerly waiting for the fix.

**Comment by rynardtspies** [comment] 2023-11-02 17:31
This issue has been addressed and will be fixed in the next release.

**Closed by rynardtspies** 2023-11-02 17:31 UTC
